### PR TITLE
[DNM] Just for CI

### PR DESCRIPTION
**Pull request by WowbaggersLiquidLunch**
Just testing if I can trigger CI on this repository.

### CODE REVIEW

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci please smoke test

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci test

**Comment by WowbaggersLiquidLunch** [comment]
hmm intersting

I can trigger full tests but not smoke tests.

**Comment by WowbaggersLiquidLunch** [comment]
@swift-ci plese test

**Comment by QuietMisdreavus** [comment]
@WowbaggersLiquidLunch SymbolKit doesn't have a separate set of "smoke tests" configured anyway; the full test run is sufficient.

**Pull request closed without merging**
