### PR TITLE
update images in docs

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
This PR updates the images used in the README and the docs to allow for the doc catalog added in https://github.com/apple/swift-docc-symbolkit/pull/6 to have proper dark-mode images.

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
LGTM, but it seems you miss the Sources/SymbolKit/SymbolKit.docc/SymbolKit.md file.

Basically it was the seem as README.md except the image reference. But due to docc was not support GitHub page yet(maybe support now?). I think it's better to keep it.

**Review by Kyle-Ye — CHANGES_REQUESTED** [review]
~Update Sources/SymbolKit/SymbolKit.docc/SymbolKit.md~

**Comment by Kyle-Ye** [comment]
I tried it locally, docc can automatically search the @x2 suffix image.

So there is no need to modify the SymbolKit.md file

My mistake. Sorry for the trouble.

**Comment by Kyle-Ye** [comment]
> #6 This looks good, thanks so much! I asked around about the images; we may want to land those separately so that we can have the documentation catalog support ready sooner.

@franklinsch  Can we accept replace the original 2 images with the new 2 pairs images since it seems hard to find the corresponding original dark-style copy?

**Review by Kyle-Ye — APPROVED** [review]

**Comment by ethan-kusters** [comment]
> > #6 This looks good, thanks so much! I asked around about the images; we may want to land those separately so that we can have the documentation catalog support ready sooner.
> 
> @franklinsch Can we accept replace the original 3 images with the new 3 pairs images since it seems hard to find the corresponding original dark-style copy?

These are the images Franklin was referring to there. I think we're good to land this. Thanks @QuietMisdreavus! This will be a big improvement.

**Review by ethan-kusters — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci please test

**Pull request merged**
